### ISSUE TITLE
[JOSS Review] Minor things

### ISSUE THREAD

**Issue by tbmiller-astro** [uw-comphys/shapelets#18]
Hello again,

Just finishing up my initial review. Great work! The paper is well written, the package is really well put together and super useful. There were just a few issues noted in some of my previous issues. A few more minor points:

- A Contributor's Guideline is missing for third parties who wish to contribute
- It's not necessary but it would be nice to upload the package to PyPI for even easier installation with pip

**Comment by mptino** [comment]
A contributor's guideline has been added to the package README with commit #21. This guideline was inspired from that of a recently published JOSS paper: https://doi.org/10.21105/joss.05994.

**Comment by nasserma** [comment]
@tbmiller-astro we have added contributor's guidelines to the readme, but will not be able to add the package to PyPI at the moment due to a conflict with the name of an [existing package](https://github.com/griffinfoster/shapelets). The developer of this older package has confirmed that it is defunct and is agreeable to our package co-opting the name and entry in PyPI, but this will take additional time.

We commit to working with the other package's developer to eventually co-opting the PyPI entry for "shapelets".

We think that this issue is essentially resolved, but wait for your confirmation.

**Comment by tbmiller-astro** [comment]
No worries, that makes sense, happy to close this issue.
